name: Welcome New Contributors

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
      - name: Check First Contribution
        run: |
          # Use GitHub API to check if this is the first contribution by the author
          # Set an environment variable or a flag if it's their first contribution
        env:
          FIRST_CONTRIBUTION: ${{ steps.check-contribution.outputs.first-contribution }}

      - name: Post Welcome Comment
        if: env.FIRST_CONTRIBUTION == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.VIVEK_TOKEN }}
          script: |
            const fs = require('fs');
            const memeData = fs.readFileSync('.github/workflows/225.png', 'base64');
            const body = `Thank you for your contribution! :tada:\n\n![Welcome Meme](data:image/png;base64,${memeData})\n\nWelcome to our community!`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

